name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # otp 22
          - elixir_version: elixir:1.9-alpine
          # otp 22
          - elixir_version: elixir:1.10-alpine
          # otp 23
          - elixir_version: elixir:1.11-alpine
    runs-on: ubuntu-latest
    container: ${{ matrix.elixir_version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add --update bash openssl git
          mix local.hex --force && mix local.rebar --force
          mix deps.get

      - name: Run linters and tests
        env:
          MIX_ENV: test
        run: mix test
